### ISSUE TITLE
next page within courses only (learning)

### ISSUE THREAD

**Issue by brandonpruitt** [ThemeFuse/Unyson-Learning-Extension#5]
Hello.

First off, I love your plugin - it is absolutely lovely.  I am trying to figure out how I can make the learning portion of unyson only allow navigation within courses, and not allow users to click to the "next" lesson unless the next lesson is a part of the same course.

For example, if I have 2 different courses

    Course 1
    Course 2

and I have 3 lessons for each course

    Lesson A
    Lesson B
    Lesson C

Once my user reaches the end of Lesson C in Course 1, I do not want the button at the bottom to appear that allows them to proceed to Lesson A of Course 2. I am unsure which file and what code to edit in order to eliminate this.

**Comment by moldcraft** [comment]
Hello,

At the moment, I don't know the answer.

*The developer that made the Learning extension is no longer in our team, and at the moment I don't have time to study the Learning extension. I will give a response but (much) later. You can try to find the answer yourself. Sorry*

**Comment by GheorgheP** [comment]
Hi,

Do you use our scratch theme reference for the lessons views? Because you cannot be directed from one course lesson to another course lesson.

Possible you use wordpress `prevous_post_link()` and `next_post_link()`. You have to use the `fw_ext_learning_get_previous_lesson()` and `fw_ext_learning_get_next_lesson()`, as is already specified in extension documentation: http://manual.unyson.io/en/latest/extension/learning/index.html#helpers

**Comment by brandonpruitt** [comment]
Hello.  Thank you for your responses.  I am using a theme called "Woffice" and they told me I should seek you out for how to accomplish this.

Before they included "learning" with Unyson, I was using standard blog posts and was able to achieve what I was after by editing Previous_post_link() and next_post_link() as you have described

but now, with this 'learning' plugin from unyson, I need to find how to accomplish the same task


You mension using

fw_ext_learning_get_previous_lesson() and fw_ext_learning_get_next_lesson()

can you please tell me which file those two pieces of code are located in, and what code I should use to replace them?  I am sorry for such a hassle, but thank you so much for your help so far

**Comment by brandonpruitt** [comment]
I am very sorry to be such a pain on this, but can you please help me figure out which file and which line of code I am supposed to change?  I have been reading your link for a week and I really cannot figure out what I am supposed to do

**Comment by moldcraft** [comment]
https://codex.wordpress.org/Function_Reference/previous_post_link

That function should be used in [learning taxonomy](https://github.com/ThemeFuse/Unyson-Learning-Extension/blob/c59285e6bd9d56093e5dc7ed702028c3e12b3c0a/class-fw-extension-learning.php#L213) templates https://developer.wordpress.org/themes/template-files-section/taxonomy-templates/

**Comment by brandonpruitt** [comment]
thank you for taking the time to respond again but unfortunately this is way too far over my head...I have no idea what you are talking about.  I will just have to seek other means for my lessons plugin.

**Comment by moldcraft** [comment]
Can you give us a link to your site or give us access to your site so we can inspect what actually is the problem? *Because we don't understand what you don't understand.*

**Comment by GheorgheP** [comment]
Hi,

So, to start from begging.
 Before you used posts for lessons ans sure you used `prevous_post_link()` and `next_post_link()` in order to navigate on lessons page. 
 You installed the **Unyson** framework with the **Learning** extensions. Created courses, created lessons to courses, all the necessary staff. You did not change any line of code, just created the courses and lessons. But when you open the last course lesson page, it shows a link to to move to the next lesson, that is already the first lesson of another course, and that is not correct.

If this is the scenario I described, them there seems to be a problem, as by default the learning doens't have to work like this, the lessons pagination stops on the last course lesson.

Could you provide a link to you installation?

In case is something private, provide details on my email address: pisarenco.gh@gmail.com.
